import { useEffect, useState, type FormEvent } from 'react';
import { Check, MessageSquare, Send, Workflow, X } from 'lucide-react';
import { apiFetch, setCsrf } from '../lib/api';

type PortalQuote = { id: string; quoteNumber: number; status: string; revision: number; totalMinor: number; customer: string; lines: Array<{ id: string; product: string; quantity: number; unitPriceMinor: number; discountBps: number }> };
const money = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value / 100);

export function CustomerPortal() {
  const [quote, setQuote] = useState<PortalQuote | null>(null); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = async () => { const response = await apiFetch<{ data: PortalQuote }>('/api/portal/quote'); setQuote(response.data); };
  useEffect(() => { void (async () => { try { const token = new URLSearchParams(location.search).get('token'); if (token) { const redeemed = await apiFetch<{ csrfToken: string }>('/api/portal/redeem', { method: 'POST', body: JSON.stringify({ token }) }); setCsrf(redeemed.csrfToken); history.replaceState({}, '', '/portal'); } await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'This link is unavailable.'); } })(); }, []);
  const respond = async (action: 'accept' | 'reject' | 'comment', event?: FormEvent) => { event?.preventDefault(); try { await apiFetch('/api/portal/quote/respond', { method: 'POST', body: JSON.stringify({ action, message: message || undefined }) }); setMessage(''); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not send response.'); } };
  const counter = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!quote) return; const form = new FormData(event.currentTarget); const lines = quote.lines.map((line) => ({ lineId: line.id, quantity: Number(form.get(`quantity-${line.id}`)), discountBps: Number(form.get(`discount-${line.id}`)) * 100 })); try { await apiFetch('/api/portal/quote/respond', { method: 'POST', body: JSON.stringify({ action: 'counteroffer', message: message || undefined, lines }) }); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not submit counteroffer.'); } };
  return <main className="portal-page"><header className="portal-header"><span className="brand-mark"><Workflow size={21} /></span><strong>DealFlow360</strong><small>Customer portal</small></header><section className="portal-card">{error && !quote ? <div className="inline-empty"><X size={22} /><strong>{error}</strong></div> : !quote ? <p>Opening quotation…</p> : <><div className="detail-hero"><div><span>Quotation Q-{String(quote.quoteNumber).padStart(4, '0')}</span><h1>{quote.customer}</h1><p>Revision {quote.revision}</p></div><span className="status-pill success">{quote.status.replaceAll('_', ' ')}</span></div><div className="portal-lines">{quote.lines.map((line) => <article key={line.id}><div><strong>{line.product}</strong><small>{line.quantity} × {money(line.unitPriceMinor)}</small></div><span>{line.discountBps / 100}% off</span></article>)}</div><div className="portal-total"><span>Total</span><strong>{money(quote.totalMinor)}</strong></div><form className="modal-form" onSubmit={counter}><label><span>Message</span><textarea value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Add a short note" /></label><details><summary>Request line changes</summary>{quote.lines.map((line) => <div className="form-columns" key={line.id}><label><span>{line.product} quantity</span><input name={`quantity-${line.id}`} type="number" min="1" defaultValue={line.quantity} /></label><label><span>Discount %</span><input name={`discount-${line.id}`} type="number" min="0" max="100" defaultValue={line.discountBps / 100} /></label></div>)}</details>{error && <p className="login-error">{error}</p>}<div className="modal-actions split"><button type="button" className="danger-action" onClick={() => void respond('reject')}><X size={16} /> Reject</button><button type="submit" className="secondary-action"><Send size={16} /> Counter</button><button type="button" className="primary-action" onClick={() => void respond('accept')}><Check size={16} /> Accept</button></div><button type="button" className="action-text-button" onClick={() => void respond('comment')}><MessageSquare size={15} /> Send comment only</button></form></>}</section></main>;
}
